<?php
/**
 * ConversionRateSummaryApi
 * PHP version 5
 *
 * @category Class
 * @package  DigitalEnablementClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Enhanced Currency Conversion Calculator
 *
 * The Enhanced Currency Conversion Calculator is a subscription-based service that provides access to Mastercard's current dates currency conversion rates as well as historical currency conversion rates. Additionally, the API provides access to European Central Bank (ECB) reference rates that European Economic Area (EEA) issuing customer may require for the purposes of compliance with EU Regulation 2019/518
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace DigitalEnablementClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use DigitalEnablementClient\ApiException;
use DigitalEnablementClient\Configuration;
use DigitalEnablementClient\HeaderSelector;
use DigitalEnablementClient\ObjectSerializer;

/**
 * ConversionRateSummaryApi Class Doc Comment
 *
 * @category Class
 * @package  DigitalEnablementClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ConversionRateSummaryApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $host_index (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $host_index = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $host_index;
    }

    /**
     * Set the host index
     *
     * @param  int Host index (required)
     */
    public function setHostIndex($host_index)
    {
        $this->hostIndex = $host_index;
    }

    /**
     * Get the host index
     *
     * @return Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getEnhancedConversionDetailsUsingGET
     *
     * getEnhancedConversionDetails
     *
     * @param  string $rate_date Date of the requested FX rates (required)
     * @param  string $trans_curr Currency of the transaction (required)
     * @param  string $trans_amt Amount in the transaction currency (required)
     * @param  string $crdhld_bill_curr Cardholder billing currency (required)
     * @param  string $bank_fee_pct Percentage mark-up/fee (if applicable) an issuer would assess a cardholder on the cross-border/cross-currency transaction (optional)
     * @param  string $bank_fee_fixed Fixed mark-up/fee (if applicable) an issuer would assess a cardholder on the cross-border/cross-currency transaction (amount in cardholder billing currency) (optional)
     *
     * @throws \DigitalEnablementClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \DigitalEnablementClient\Model\EnhancedCurrencyConversionResponse|\DigitalEnablementClient\Model\ErrorResponse|\DigitalEnablementClient\Model\ErrorResponse|\DigitalEnablementClient\Model\ErrorResponse|\DigitalEnablementClient\Model\ErrorResponse|\DigitalEnablementClient\Model\ErrorResponse
     */
    public function getEnhancedConversionDetailsUsingGET($rate_date, $trans_curr, $trans_amt, $crdhld_bill_curr, $bank_fee_pct = null, $bank_fee_fixed = null)
    {
        list($response) = $this->getEnhancedConversionDetailsUsingGETWithHttpInfo($rate_date, $trans_curr, $trans_amt, $crdhld_bill_curr, $bank_fee_pct, $bank_fee_fixed);
        return $response;
    }

    /**
     * Operation getEnhancedConversionDetailsUsingGETWithHttpInfo
     *
     * getEnhancedConversionDetails
     *
     * @param  string $rate_date Date of the requested FX rates (required)
     * @param  string $trans_curr Currency of the transaction (required)
     * @param  string $trans_amt Amount in the transaction currency (required)
     * @param  string $crdhld_bill_curr Cardholder billing currency (required)
     * @param  string $bank_fee_pct Percentage mark-up/fee (if applicable) an issuer would assess a cardholder on the cross-border/cross-currency transaction (optional)
     * @param  string $bank_fee_fixed Fixed mark-up/fee (if applicable) an issuer would assess a cardholder on the cross-border/cross-currency transaction (amount in cardholder billing currency) (optional)
     *
     * @throws \DigitalEnablementClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \DigitalEnablementClient\Model\EnhancedCurrencyConversionResponse|\DigitalEnablementClient\Model\ErrorResponse|\DigitalEnablementClient\Model\ErrorResponse|\DigitalEnablementClient\Model\ErrorResponse|\DigitalEnablementClient\Model\ErrorResponse|\DigitalEnablementClient\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getEnhancedConversionDetailsUsingGETWithHttpInfo($rate_date, $trans_curr, $trans_amt, $crdhld_bill_curr, $bank_fee_pct = null, $bank_fee_fixed = null)
    {
        $request = $this->getEnhancedConversionDetailsUsingGETRequest($rate_date, $trans_curr, $trans_amt, $crdhld_bill_curr, $bank_fee_pct, $bank_fee_fixed);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\DigitalEnablementClient\Model\EnhancedCurrencyConversionResponse' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\DigitalEnablementClient\Model\EnhancedCurrencyConversionResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\DigitalEnablementClient\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\DigitalEnablementClient\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\DigitalEnablementClient\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\DigitalEnablementClient\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\DigitalEnablementClient\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\DigitalEnablementClient\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\DigitalEnablementClient\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\DigitalEnablementClient\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\DigitalEnablementClient\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\DigitalEnablementClient\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\DigitalEnablementClient\Model\EnhancedCurrencyConversionResponse';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DigitalEnablementClient\Model\EnhancedCurrencyConversionResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DigitalEnablementClient\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DigitalEnablementClient\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DigitalEnablementClient\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DigitalEnablementClient\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DigitalEnablementClient\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getEnhancedConversionDetailsUsingGETAsync
     *
     * getEnhancedConversionDetails
     *
     * @param  string $rate_date Date of the requested FX rates (required)
     * @param  string $trans_curr Currency of the transaction (required)
     * @param  string $trans_amt Amount in the transaction currency (required)
     * @param  string $crdhld_bill_curr Cardholder billing currency (required)
     * @param  string $bank_fee_pct Percentage mark-up/fee (if applicable) an issuer would assess a cardholder on the cross-border/cross-currency transaction (optional)
     * @param  string $bank_fee_fixed Fixed mark-up/fee (if applicable) an issuer would assess a cardholder on the cross-border/cross-currency transaction (amount in cardholder billing currency) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getEnhancedConversionDetailsUsingGETAsync($rate_date, $trans_curr, $trans_amt, $crdhld_bill_curr, $bank_fee_pct = null, $bank_fee_fixed = null)
    {
        return $this->getEnhancedConversionDetailsUsingGETAsyncWithHttpInfo($rate_date, $trans_curr, $trans_amt, $crdhld_bill_curr, $bank_fee_pct, $bank_fee_fixed)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getEnhancedConversionDetailsUsingGETAsyncWithHttpInfo
     *
     * getEnhancedConversionDetails
     *
     * @param  string $rate_date Date of the requested FX rates (required)
     * @param  string $trans_curr Currency of the transaction (required)
     * @param  string $trans_amt Amount in the transaction currency (required)
     * @param  string $crdhld_bill_curr Cardholder billing currency (required)
     * @param  string $bank_fee_pct Percentage mark-up/fee (if applicable) an issuer would assess a cardholder on the cross-border/cross-currency transaction (optional)
     * @param  string $bank_fee_fixed Fixed mark-up/fee (if applicable) an issuer would assess a cardholder on the cross-border/cross-currency transaction (amount in cardholder billing currency) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getEnhancedConversionDetailsUsingGETAsyncWithHttpInfo($rate_date, $trans_curr, $trans_amt, $crdhld_bill_curr, $bank_fee_pct = null, $bank_fee_fixed = null)
    {
        $returnType = '\DigitalEnablementClient\Model\EnhancedCurrencyConversionResponse';
        $request = $this->getEnhancedConversionDetailsUsingGETRequest($rate_date, $trans_curr, $trans_amt, $crdhld_bill_curr, $bank_fee_pct, $bank_fee_fixed);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getEnhancedConversionDetailsUsingGET'
     *
     * @param  string $rate_date Date of the requested FX rates (required)
     * @param  string $trans_curr Currency of the transaction (required)
     * @param  string $trans_amt Amount in the transaction currency (required)
     * @param  string $crdhld_bill_curr Cardholder billing currency (required)
     * @param  string $bank_fee_pct Percentage mark-up/fee (if applicable) an issuer would assess a cardholder on the cross-border/cross-currency transaction (optional)
     * @param  string $bank_fee_fixed Fixed mark-up/fee (if applicable) an issuer would assess a cardholder on the cross-border/cross-currency transaction (amount in cardholder billing currency) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getEnhancedConversionDetailsUsingGETRequest($rate_date, $trans_curr, $trans_amt, $crdhld_bill_curr, $bank_fee_pct = null, $bank_fee_fixed = null)
    {
        // verify the required parameter 'rate_date' is set
        if ($rate_date === null || (is_array($rate_date) && count($rate_date) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $rate_date when calling getEnhancedConversionDetailsUsingGET'
            );
        }
        // verify the required parameter 'trans_curr' is set
        if ($trans_curr === null || (is_array($trans_curr) && count($trans_curr) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $trans_curr when calling getEnhancedConversionDetailsUsingGET'
            );
        }
        // verify the required parameter 'trans_amt' is set
        if ($trans_amt === null || (is_array($trans_amt) && count($trans_amt) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $trans_amt when calling getEnhancedConversionDetailsUsingGET'
            );
        }
        // verify the required parameter 'crdhld_bill_curr' is set
        if ($crdhld_bill_curr === null || (is_array($crdhld_bill_curr) && count($crdhld_bill_curr) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $crdhld_bill_curr when calling getEnhancedConversionDetailsUsingGET'
            );
        }

        $resourcePath = '/summary-rates';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($rate_date !== null) {
            if('form' === 'form' && is_array($rate_date)) {
                foreach($rate_date as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['rate_date'] = $rate_date;
            }
        }
        // query params
        if ($trans_curr !== null) {
            if('form' === 'form' && is_array($trans_curr)) {
                foreach($trans_curr as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['trans_curr'] = $trans_curr;
            }
        }
        // query params
        if ($trans_amt !== null) {
            if('form' === 'form' && is_array($trans_amt)) {
                foreach($trans_amt as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['trans_amt'] = $trans_amt;
            }
        }
        // query params
        if ($crdhld_bill_curr !== null) {
            if('form' === 'form' && is_array($crdhld_bill_curr)) {
                foreach($crdhld_bill_curr as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['crdhld_bill_curr'] = $crdhld_bill_curr;
            }
        }
        // query params
        if ($bank_fee_pct !== null) {
            if('form' === 'form' && is_array($bank_fee_pct)) {
                foreach($bank_fee_pct as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['bank_fee_pct'] = $bank_fee_pct;
            }
        }
        // query params
        if ($bank_fee_fixed !== null) {
            if('form' === 'form' && is_array($bank_fee_fixed)) {
                foreach($bank_fee_fixed as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['bank_fee_fixed'] = $bank_fee_fixed;
            }
        }



        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
