/**
 * Enhanced Currency Conversion Calculator
 * The Enhanced Currency Conversion Calculator is a subscription-based service that provides access to Mastercard's current dates currency conversion rates as well as historical currency conversion rates. Additionally, the API provides access to European Central Bank (ECB) reference rates that European Economic Area (EEA) issuing customer may require for the purposes of compliance with EU Regulation 2019/518
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ECBConversionObject model module.
 * @module model/ECBConversionObject
 * @version 1.0.0
 */
class ECBConversionObject {
    /**
     * Constructs a new <code>ECBConversionObject</code>.
     * @alias module:model/ECBConversionObject
     */
    constructor() { 
        
        ECBConversionObject.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ECBConversionObject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ECBConversionObject} obj Optional instance to populate.
     * @return {module:model/ECBConversionObject} The populated <code>ECBConversionObject</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ECBConversionObject();

            if (data.hasOwnProperty('ecbReferenceRate')) {
                obj['ecbReferenceRate'] = ApiClient.convertToType(data['ecbReferenceRate'], 'Number');
            }
            if (data.hasOwnProperty('ecbReferenceRateDate')) {
                obj['ecbReferenceRateDate'] = ApiClient.convertToType(data['ecbReferenceRateDate'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('reasonCode')) {
                obj['reasonCode'] = ApiClient.convertToType(data['reasonCode'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Euro foreign exchange reference rates issued by the European Central Bank (ECB). When neither the transaction currency nor the cardholder billing currency is equal to Euro, a calculated reference rate is derived from the two ECB rates
 * @member {Number} ecbReferenceRate
 */
ECBConversionObject.prototype['ecbReferenceRate'] = undefined;

/**
 * Date of reference rates issued by the European Central Bank (ECB).
 * @member {String} ecbReferenceRateDate
 */
ECBConversionObject.prototype['ecbReferenceRateDate'] = undefined;

/**
 * User friendly message (if applicable)
 * @member {String} message
 */
ECBConversionObject.prototype['message'] = undefined;

/**
 * User friendly reason code (if applicable)
 * @member {String} reasonCode
 */
ECBConversionObject.prototype['reasonCode'] = undefined;






export default ECBConversionObject;

