/**
 * Enhanced Currency Conversion Calculator
 * The Enhanced Currency Conversion Calculator is a subscription-based service that provides access to Mastercard's current dates currency conversion rates as well as historical currency conversion rates. Additionally, the API provides access to European Central Bank (ECB) reference rates that European Economic Area (EEA) issuing customer may require for the purposes of compliance with EU Regulation 2019/518
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EcbError model module.
 * @module model/EcbError
 * @version 1.0.0
 */
class EcbError {
    /**
     * Constructs a new <code>EcbError</code>.
     * @alias module:model/EcbError
     */
    constructor() { 
        
        EcbError.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EcbError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EcbError} obj Optional instance to populate.
     * @return {module:model/EcbError} The populated <code>EcbError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EcbError();

            if (data.hasOwnProperty('Description')) {
                obj['Description'] = ApiClient.convertToType(data['Description'], 'String');
            }
            if (data.hasOwnProperty('Details')) {
                obj['Details'] = ApiClient.convertToType(data['Details'], 'String');
            }
            if (data.hasOwnProperty('ReasonCode')) {
                obj['ReasonCode'] = ApiClient.convertToType(data['ReasonCode'], 'String');
            }
            if (data.hasOwnProperty('Recoverable')) {
                obj['Recoverable'] = ApiClient.convertToType(data['Recoverable'], 'Boolean');
            }
            if (data.hasOwnProperty('Source')) {
                obj['Source'] = ApiClient.convertToType(data['Source'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Short description of the ReasonCode field.
 * @member {String} Description
 */
EcbError.prototype['Description'] = undefined;

/**
 * Where appropriate, indicates detailed information about data received and calculated during request processing, to help the user with diagnosing errors.
 * @member {String} Details
 */
EcbError.prototype['Details'] = undefined;

/**
 * A unique constant identifying the error case encountered during transaction processing. For example, INVALID_SIGNATURE is used when the request signature does not match the expected one.
 * @member {String} ReasonCode
 */
EcbError.prototype['ReasonCode'] = undefined;

/**
 * Indicates whether this error will always be returned for this request, or retrying could change the outcome. For example, if the request contains an invalid   signature, retrying will never result in a success. However, if the error is related to some unexpected timeout with the service, retrying the call could result in a successful response.
 * @member {Boolean} Recoverable
 */
EcbError.prototype['Recoverable'] = undefined;

/**
 * The name of the application that generated this error
 * @member {String} Source
 */
EcbError.prototype['Source'] = undefined;






export default EcbError;

