/**
 * Enhanced Currency Conversion Calculator
 * The Enhanced Currency Conversion Calculator is a subscription-based service that provides access to Mastercard's current dates currency conversion rates as well as historical currency conversion rates. Additionally, the API provides access to European Central Bank (ECB) reference rates that European Economic Area (EEA) issuing customer may require for the purposes of compliance with EU Regulation 2019/518
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EcbMcRateIssued from './EcbMcRateIssued';

/**
 * The EnhancedSettlementRateIssued model module.
 * @module model/EnhancedSettlementRateIssued
 * @version 1.0.0
 */
class EnhancedSettlementRateIssued {
    /**
     * Constructs a new <code>EnhancedSettlementRateIssued</code>.
     * @alias module:model/EnhancedSettlementRateIssued
     */
    constructor() { 
        
        EnhancedSettlementRateIssued.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EnhancedSettlementRateIssued</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EnhancedSettlementRateIssued} obj Optional instance to populate.
     * @return {module:model/EnhancedSettlementRateIssued} The populated <code>EnhancedSettlementRateIssued</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EnhancedSettlementRateIssued();

            if (data.hasOwnProperty('ecbRateIssued')) {
                obj['ecbRateIssued'] = EcbMcRateIssued.constructFromObject(data['ecbRateIssued']);
            }
            if (data.hasOwnProperty('mastercardRateIssued')) {
                obj['mastercardRateIssued'] = EcbMcRateIssued.constructFromObject(data['mastercardRateIssued']);
            }
            if (data.hasOwnProperty('rateDate')) {
                obj['rateDate'] = ApiClient.convertToType(data['rateDate'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/EcbMcRateIssued} ecbRateIssued
 */
EnhancedSettlementRateIssued.prototype['ecbRateIssued'] = undefined;

/**
 * @member {module:model/EcbMcRateIssued} mastercardRateIssued
 */
EnhancedSettlementRateIssued.prototype['mastercardRateIssued'] = undefined;

/**
 * The date of the requested rates
 * @member {String} rateDate
 */
EnhancedSettlementRateIssued.prototype['rateDate'] = undefined;






export default EnhancedSettlementRateIssued;

