/**
 * Enhanced Currency Conversion Calculator
 * The Enhanced Currency Conversion Calculator is a subscription-based service that provides access to Mastercard's current dates currency conversion rates as well as historical currency conversion rates. Additionally, the API provides access to European Central Bank (ECB) reference rates that European Economic Area (EEA) issuing customer may require for the purposes of compliance with EU Regulation 2019/518
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MastercardConversionObject model module.
 * @module model/MastercardConversionObject
 * @version 1.0.0
 */
class MastercardConversionObject {
    /**
     * Constructs a new <code>MastercardConversionObject</code>.
     * @alias module:model/MastercardConversionObject
     */
    constructor() { 
        
        MastercardConversionObject.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MastercardConversionObject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MastercardConversionObject} obj Optional instance to populate.
     * @return {module:model/MastercardConversionObject} The populated <code>MastercardConversionObject</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MastercardConversionObject();

            if (data.hasOwnProperty('crdhldBillAmtExclAllFees')) {
                obj['crdhldBillAmtExclAllFees'] = ApiClient.convertToType(data['crdhldBillAmtExclAllFees'], 'Number');
            }
            if (data.hasOwnProperty('crdhldBillAmtInclAllFees')) {
                obj['crdhldBillAmtInclAllFees'] = ApiClient.convertToType(data['crdhldBillAmtInclAllFees'], 'Number');
            }
            if (data.hasOwnProperty('mastercardConvRateExclAllFees')) {
                obj['mastercardConvRateExclAllFees'] = ApiClient.convertToType(data['mastercardConvRateExclAllFees'], 'Number');
            }
            if (data.hasOwnProperty('mastercardConvRateInclPctFee')) {
                obj['mastercardConvRateInclPctFee'] = ApiClient.convertToType(data['mastercardConvRateInclPctFee'], 'Number');
            }
            if (data.hasOwnProperty('mastercardFxRateDate')) {
                obj['mastercardFxRateDate'] = ApiClient.convertToType(data['mastercardFxRateDate'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('reasonCode')) {
                obj['reasonCode'] = ApiClient.convertToType(data['reasonCode'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Cardholder billing amount calculated by using the Mastercard conversion rate, excluding any applicable issuer-to-cardholder fees
 * @member {Number} crdhldBillAmtExclAllFees
 */
MastercardConversionObject.prototype['crdhldBillAmtExclAllFees'] = undefined;

/**
 * Cardholder Billing Amount as calculated by applying the Mastercard Conversion Rate, including any applicable issuer-to-cardholder fees (percentage and fixed)
 * @member {Number} crdhldBillAmtInclAllFees
 */
MastercardConversionObject.prototype['crdhldBillAmtInclAllFees'] = undefined;

/**
 * Mastercard exchange rate for the requested currency pair excluding any issuer-to-cardholder fees
 * @member {Number} mastercardConvRateExclAllFees
 */
MastercardConversionObject.prototype['mastercardConvRateExclAllFees'] = undefined;

/**
 * Mastercard exchange rate for the requested currency pair including issuer-to-cardholder percentage rate fee as provided by the issuer in the API call
 * @member {Number} mastercardConvRateInclPctFee
 */
MastercardConversionObject.prototype['mastercardConvRateInclPctFee'] = undefined;

/**
 * Date of Mastercard issued conversion rates. The date can differ to the requested rate date if no new rates are published for the requested date or if the user requests for a historical date
 * @member {String} mastercardFxRateDate
 */
MastercardConversionObject.prototype['mastercardFxRateDate'] = undefined;

/**
 * User friendly message (if applicable)
 * @member {String} message
 */
MastercardConversionObject.prototype['message'] = undefined;

/**
 * User friendly reason code (if applicable)
 * @member {String} reasonCode
 */
MastercardConversionObject.prototype['reasonCode'] = undefined;






export default MastercardConversionObject;

