/**
 * Enhanced Currency Conversion Calculator
 * The Enhanced Currency Conversion Calculator is a subscription-based service that provides access to Mastercard's current dates currency conversion rates as well as historical currency conversion rates. Additionally, the API provides access to European Central Bank (ECB) reference rates that European Economic Area (EEA) issuing customer may require for the purposes of compliance with EU Regulation 2019/518
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EnhancedSettlementRateIssuedResponse', 'model/ErrorResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/EnhancedSettlementRateIssuedResponse'), require('../model/ErrorResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.EnhancedCurrencyConversionCalculator) {
      root.EnhancedCurrencyConversionCalculator = {};
    }
    root.EnhancedCurrencyConversionCalculator.ConversionRateIssuedApi = factory(root.EnhancedCurrencyConversionCalculator.ApiClient, root.EnhancedCurrencyConversionCalculator.EnhancedSettlementRateIssuedResponse, root.EnhancedCurrencyConversionCalculator.ErrorResponse);
  }
}(this, function(ApiClient, EnhancedSettlementRateIssuedResponse, ErrorResponse) {
  'use strict';

  /**
   * ConversionRateIssued service.
   * @module api/ConversionRateIssuedApi
   * @version 1.0.0
   */

  /**
   * Constructs a new ConversionRateIssuedApi. 
   * @alias module:api/ConversionRateIssuedApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the isEcbMcRateIssuedUsingGET operation.
     * @callback module:api/ConversionRateIssuedApi~isEcbMcRateIssuedUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/EnhancedSettlementRateIssuedResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * isEcbMcRateIssued
     * @param {Object} opts Optional parameters
     * @param {String} opts.requestDate Rate issued date (YYYY-mm-dd)
     * @param {module:api/ConversionRateIssuedApi~isEcbMcRateIssuedUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/EnhancedSettlementRateIssuedResponse}
     */
    this.isEcbMcRateIssuedUsingGET = function(opts, callback) {
      opts = opts || {};
      var postBody = null;

      var pathParams = {
      };
      var queryParams = {
        'request_date': opts['requestDate'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = EnhancedSettlementRateIssuedResponse;
      return this.apiClient.callApi(
        '/rate-statuses', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }
  };

  return exports;
}));
