/**
 * Enhanced Currency Conversion Calculator
 * The Enhanced Currency Conversion Calculator is a subscription-based service that provides access to Mastercard's current dates currency conversion rates as well as historical currency conversion rates. Additionally, the API provides access to European Central Bank (ECB) reference rates that European Economic Area (EEA) issuing customer may require for the purposes of compliance with EU Regulation 2019/518
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EnhancedCurrencyConversionResponse', 'model/ErrorResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/EnhancedCurrencyConversionResponse'), require('../model/ErrorResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.EnhancedCurrencyConversionCalculator) {
      root.EnhancedCurrencyConversionCalculator = {};
    }
    root.EnhancedCurrencyConversionCalculator.ConversionRateSummaryApi = factory(root.EnhancedCurrencyConversionCalculator.ApiClient, root.EnhancedCurrencyConversionCalculator.EnhancedCurrencyConversionResponse, root.EnhancedCurrencyConversionCalculator.ErrorResponse);
  }
}(this, function(ApiClient, EnhancedCurrencyConversionResponse, ErrorResponse) {
  'use strict';

  /**
   * ConversionRateSummary service.
   * @module api/ConversionRateSummaryApi
   * @version 1.0.0
   */

  /**
   * Constructs a new ConversionRateSummaryApi. 
   * @alias module:api/ConversionRateSummaryApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getEnhancedConversionDetailsUsingGET operation.
     * @callback module:api/ConversionRateSummaryApi~getEnhancedConversionDetailsUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/EnhancedCurrencyConversionResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getEnhancedConversionDetails
     * @param {String} rateDate Date of the requested FX rates
     * @param {String} transCurr Currency of the transaction
     * @param {String} transAmt Amount in the transaction currency
     * @param {String} crdhldBillCurr Cardholder billing currency
     * @param {Object} opts Optional parameters
     * @param {String} opts.bankFeePct Percentage mark-up/fee (if applicable) an issuer would assess a cardholder on the cross-border/cross-currency transaction
     * @param {String} opts.bankFeeFixed Fixed mark-up/fee (if applicable) an issuer would assess a cardholder on the cross-border/cross-currency transaction (amount in cardholder billing currency)
     * @param {module:api/ConversionRateSummaryApi~getEnhancedConversionDetailsUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/EnhancedCurrencyConversionResponse}
     */
    this.getEnhancedConversionDetailsUsingGET = function(rateDate, transCurr, transAmt, crdhldBillCurr, opts, callback) {
      opts = opts || {};
      var postBody = null;
      // verify the required parameter 'rateDate' is set
      if (rateDate === undefined || rateDate === null) {
        throw new Error("Missing the required parameter 'rateDate' when calling getEnhancedConversionDetailsUsingGET");
      }
      // verify the required parameter 'transCurr' is set
      if (transCurr === undefined || transCurr === null) {
        throw new Error("Missing the required parameter 'transCurr' when calling getEnhancedConversionDetailsUsingGET");
      }
      // verify the required parameter 'transAmt' is set
      if (transAmt === undefined || transAmt === null) {
        throw new Error("Missing the required parameter 'transAmt' when calling getEnhancedConversionDetailsUsingGET");
      }
      // verify the required parameter 'crdhldBillCurr' is set
      if (crdhldBillCurr === undefined || crdhldBillCurr === null) {
        throw new Error("Missing the required parameter 'crdhldBillCurr' when calling getEnhancedConversionDetailsUsingGET");
      }

      var pathParams = {
      };
      var queryParams = {
        'rate_date': rateDate,
        'trans_curr': transCurr,
        'trans_amt': transAmt,
        'crdhld_bill_curr': crdhldBillCurr,
        'bank_fee_pct': opts['bankFeePct'],
        'bank_fee_fixed': opts['bankFeeFixed'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = EnhancedCurrencyConversionResponse;
      return this.apiClient.callApi(
        '/summary-rates', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }
  };

  return exports;
}));
