/**
 * Enhanced Currency Conversion Calculator
 * The Enhanced Currency Conversion Calculator is a subscription-based service that provides access to Mastercard's current dates currency conversion rates as well as historical currency conversion rates. Additionally, the API provides access to European Central Bank (ECB) reference rates that European Economic Area (EEA) issuing customer may require for the purposes of compliance with EU Regulation 2019/518
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import EnhancedSettlementRateIssuedResponse from '../model/EnhancedSettlementRateIssuedResponse';
import ErrorResponse from '../model/ErrorResponse';

/**
* ConversionRateIssued service.
* @module api/ConversionRateIssuedApi
* @version 1.0.0
*/
export default class ConversionRateIssuedApi {

    /**
    * Constructs a new ConversionRateIssuedApi. 
    * @alias module:api/ConversionRateIssuedApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the isEcbMcRateIssuedUsingGET operation.
     * @callback module:api/ConversionRateIssuedApi~isEcbMcRateIssuedUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/EnhancedSettlementRateIssuedResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * isEcbMcRateIssued
     * @param {Object} opts Optional parameters
     * @param {String} opts.requestDate Rate issued date (YYYY-mm-dd)
     * @param {module:api/ConversionRateIssuedApi~isEcbMcRateIssuedUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/EnhancedSettlementRateIssuedResponse}
     */
    isEcbMcRateIssuedUsingGET(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'request_date': opts['requestDate']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = EnhancedSettlementRateIssuedResponse;
      return this.apiClient.callApi(
        '/rate-statuses', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
