/**
 * Enhanced Currency Conversion Calculator
 * The Enhanced Currency Conversion Calculator is a subscription-based service that provides access to Mastercard's current dates currency conversion rates as well as historical currency conversion rates. Additionally, the API provides access to European Central Bank (ECB) reference rates that European Economic Area (EEA) issuing customer may require for the purposes of compliance with EU Regulation 2019/518
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EnhancedEcbCurrencyResponse', 'model/ErrorResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/EnhancedEcbCurrencyResponse'), require('../model/ErrorResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.EnhancedCurrencyConversionCalculator) {
      root.EnhancedCurrencyConversionCalculator = {};
    }
    root.EnhancedCurrencyConversionCalculator.EcbCurrenciesApi = factory(root.EnhancedCurrencyConversionCalculator.ApiClient, root.EnhancedCurrencyConversionCalculator.EnhancedEcbCurrencyResponse, root.EnhancedCurrencyConversionCalculator.ErrorResponse);
  }
}(this, function(ApiClient, EnhancedEcbCurrencyResponse, ErrorResponse) {
  'use strict';

  /**
   * EcbCurrencies service.
   * @module api/EcbCurrenciesApi
   * @version 1.0.0
   */

  /**
   * Constructs a new EcbCurrenciesApi. 
   * @alias module:api/EcbCurrenciesApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getEcbCurrenciesListUsingGET operation.
     * @callback module:api/EcbCurrenciesApi~getEcbCurrenciesListUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/EnhancedEcbCurrencyResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getEcbCurrenciesList
     * @param {module:api/EcbCurrenciesApi~getEcbCurrenciesListUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/EnhancedEcbCurrencyResponse}
     */
    this.getEcbCurrenciesListUsingGET = function(callback) {
      var postBody = null;

      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = EnhancedEcbCurrencyResponse;
      return this.apiClient.callApi(
        '/ecb-currencies', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }
  };

  return exports;
}));
