/**
 * Enhanced Currency Conversion Calculator
 * The Enhanced Currency Conversion Calculator is a subscription-based service that provides access to Mastercard's current dates currency conversion rates as well as historical currency conversion rates. Additionally, the API provides access to European Central Bank (ECB) reference rates that European Economic Area (EEA) issuing customer may require for the purposes of compliance with EU Regulation 2019/518
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import EnhancedEcbCurrencyResponse from '../model/EnhancedEcbCurrencyResponse';
import ErrorResponse from '../model/ErrorResponse';

/**
* EcbCurrencies service.
* @module api/EcbCurrenciesApi
* @version 1.0.0
*/
export default class EcbCurrenciesApi {

    /**
    * Constructs a new EcbCurrenciesApi. 
    * @alias module:api/EcbCurrenciesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getEcbCurrenciesListUsingGET operation.
     * @callback module:api/EcbCurrenciesApi~getEcbCurrenciesListUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/EnhancedEcbCurrencyResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getEcbCurrenciesList
     * @param {module:api/EcbCurrenciesApi~getEcbCurrenciesListUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/EnhancedEcbCurrencyResponse}
     */
    getEcbCurrenciesListUsingGET(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = EnhancedEcbCurrencyResponse;
      return this.apiClient.callApi(
        '/ecb-currencies', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
