<?php
/**
 * MastercardConversionObjectTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DigitalEnablementClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Enhanced Currency Conversion Calculator
 *
 * The Enhanced Currency Conversion Calculator is a subscription-based service that provides access to Mastercard's current dates currency conversion rates as well as historical currency conversion rates. Additionally, the API provides access to European Central Bank (ECB) reference rates that European Economic Area (EEA) issuing customer may require for the purposes of compliance with EU Regulation 2019/518
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace DigitalEnablementClient;

use PHPUnit\Framework\TestCase;

/**
 * MastercardConversionObjectTest Class Doc Comment
 *
 * @category    Class
 * @description MastercardConversionObject
 * @package     DigitalEnablementClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MastercardConversionObjectTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MastercardConversionObject"
     */
    public function testMastercardConversionObject()
    {
    }

    /**
     * Test attribute "crdhld_bill_amt_excl_all_fees"
     */
    public function testPropertyCrdhldBillAmtExclAllFees()
    {
    }

    /**
     * Test attribute "crdhld_bill_amt_incl_all_fees"
     */
    public function testPropertyCrdhldBillAmtInclAllFees()
    {
    }

    /**
     * Test attribute "mastercard_conv_rate_excl_all_fees"
     */
    public function testPropertyMastercardConvRateExclAllFees()
    {
    }

    /**
     * Test attribute "mastercard_conv_rate_incl_pct_fee"
     */
    public function testPropertyMastercardConvRateInclPctFee()
    {
    }

    /**
     * Test attribute "mastercard_fx_rate_date"
     */
    public function testPropertyMastercardFxRateDate()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }

    /**
     * Test attribute "reason_code"
     */
    public function testPropertyReasonCode()
    {
    }
}
