<?php
/**
 * EnhancedCurrencyConversionDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DigitalEnablementClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Enhanced Currency Conversion Calculator
 *
 * The Enhanced Currency Conversion Calculator is a subscription-based service that provides access to Mastercard's current dates currency conversion rates as well as historical currency conversion rates. Additionally, the API provides access to European Central Bank (ECB) reference rates that European Economic Area (EEA) issuing customer may require for the purposes of compliance with EU Regulation 2019/518
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace DigitalEnablementClient;

use PHPUnit\Framework\TestCase;

/**
 * EnhancedCurrencyConversionDataTest Class Doc Comment
 *
 * @category    Class
 * @description EnhancedCurrencyConversionData
 * @package     DigitalEnablementClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EnhancedCurrencyConversionDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EnhancedCurrencyConversionData"
     */
    public function testEnhancedCurrencyConversionData()
    {
    }

    /**
     * Test attribute "trans_curr"
     */
    public function testPropertyTransCurr()
    {
    }

    /**
     * Test attribute "crdhld_bill_curr"
     */
    public function testPropertyCrdhldBillCurr()
    {
    }

    /**
     * Test attribute "rate_date"
     */
    public function testPropertyRateDate()
    {
    }

    /**
     * Test attribute "trans_amt"
     */
    public function testPropertyTransAmt()
    {
    }

    /**
     * Test attribute "bank_fee_pct"
     */
    public function testPropertyBankFeePct()
    {
    }

    /**
     * Test attribute "bank_fee_fixed"
     */
    public function testPropertyBankFeeFixed()
    {
    }

    /**
     * Test attribute "mastercard"
     */
    public function testPropertyMastercard()
    {
    }

    /**
     * Test attribute "ecb"
     */
    public function testPropertyEcb()
    {
    }

    /**
     * Test attribute "effective_conversion_rate"
     */
    public function testPropertyEffectiveConversionRate()
    {
    }

    /**
     * Test attribute "pct_difference_mastercard_excl_all_fees_and_ecb"
     */
    public function testPropertyPctDifferenceMastercardExclAllFeesAndEcb()
    {
    }

    /**
     * Test attribute "pct_difference_mastercard_incl_all_fees_and_ecb"
     */
    public function testPropertyPctDifferenceMastercardInclAllFeesAndEcb()
    {
    }
}
